name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Install Node 18
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: cd auth && npm install && npm run test:ci
