name: tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd auth && npm install && npm run test:ci
